### PR TITLE
Workflow process aim

### PR DESCRIPTION
**Pull request by sanjaygupta972004**
@maityamit    created work flow, process ,aim

### CODE REVIEW

**Comment by sanjaygupta972004** [comment]
#81

**Comment by sanjaygupta972004** [comment]
@maityamit

**Comment by maityamit** [comment]
@sanjaygupta972004 iwoc or JGEC Winter of code ?

**Review by maityamit — APPROVED** [review]

**Comment by sanjaygupta972004** [comment]
@maityamit it is correct then please it marege and close issue

**Comment by sanjaygupta972004** [comment]
> @sanjaygupta972004 iwoc or JGEC Winter of code ?

IWOC

**Pull request merged**
